[Command]
name = "especial1"
command = ~D, DF, F, D, F, y
time = 30
[Command]
name = "especial2"
command = ~D, DB, B, D, B, y
time = 30
[Command]
name = "especial3"
command = ~D, DB, B, D, B, b
time = 30
[Command]
name = "especial4"
command = ~D, DB, B, D, B, a
time = 30
[Command]
name = "especial5"
command = ~D, DF, F, D, F, b
time = 30
[Command]
name = "especial6"
command = ~D, DF, F, D, DF, F, a
time = 30
[Command]
name = "especial7"
command = ~D, DF, F, D, DF, F, a
time = 30
[Command]
name = "especial8"
command = ~D, DF, F, D, DF, F, x
time = 30
[Command]
name = "especial9"
command = ~D, DB, B, D, DB, B, x
time = 30
[Command]
name = "especial10"
command = ~D, DF, F, D, DF, F, x
time = 30
[Command]
name = "especial11"
command = ~D, DB, B, D, DF, F, y
time = 30
[Command]
name = "QCF_a"
command = ~D, DF, F, a
[Command]
name = "QCF_b"
command = ~B, F, b
[Command]
name = "super_soco"
command = ~B, F, a
[Command]
name = "rising_punch"
command = /U, a
[Command]
name = "stomp_kick"
command = /D, b
[Command]
name = "downwards_fireball"
command = /D, y
[Command]
name = "upwards_fireball"
command = /U, y
[Command]
name = "seeker_fireball"
command = ~D, DB, B, y
[Command]
name = "kiai_ho"
command = ~B, F, y
[Command]
name = "terremoto"
command = ~D, B, a
[Command]
name = "masenko"
command = ~B, D, F, y
[Command]
name = "masenko1"
command = ~B, D, F, y
[Command]
name = "ki_burn"
command = ~D, U, y
time = 50
[Command]
name = "QCF_b1"
command = ~D, DF, F, b
[Command]
name = "QCF_b2"
command = ~D, F, b
[Command]
name = "QCF_a1"
command = ~F, D, DF, F, a
[Command]
name = "QCF_b3"
command = ~F, D, DF, F, b
[Command]
name = "QCF_y"
command = ~D, DF, F, y
[Command]
name = "QCF_ya"
command = ~D, DF, F, y
[Command]
name = "QCF_z"
command = ~D, DF, F, z
[Command]
name = "QCB_a"
command = ~D, DB, B, a
[Command]
name = "fly"
command = a+b
[Command]
name = "QCB_c"
command = ~D, DB, B, c
[Command]
name = "zankuukyaku"
command = ~D, F, b
[Command]
name = "QCB_y"
command = ~D, DB, B, F, y
[Command]
name = "QCB_z"
command = ~D, DB, B, z
[Command]
name = "uppercut_a"
command = ~F, D, DF, a
[Command]
name = "uppercut_b"
command = ~F, D, DF, b
[Command]
name = "uppercut_c"
command = ~F, D, DF, c
[Command]
name = "uppercut_x"
command = ~F, D, DF, x
[Command]
name = "uppercut_y"
command = ~F, D, DF, y
[Command]
name = "uppercut_z"
command = ~F, D, DF, z
[Command]
name = "chargedownup_a"
command = ~60$D, U, a
time = 10
[Command]
name = "chargedownup_b"
command = ~60$D, U, b
time = 10
[Command]
name = "chargedownup_c"
command = ~60$D, U, c
time = 10
[Command]
name = "chargedownup_x"
command = ~60$D, U, x
time = 10
[Command]
name = "chargedownup_y"
command = ~60$D, U, y
time = 10
[Command]
name = "chargedownup_z"
command = ~60$D, U, z
time = 10
[Command]
name = "chargebackfwd_a"
command = ~60$B, F, a
time = 10
[Command]
name = "chargebackfwd_b"
command = ~60$B, F, b
time = 10
[Command]
name = "chargedownup_c"
command = ~60$D, U, c
time = 10
[Command]
name = "chargedownup_x"
command = ~60$D, U, x
time = 10
[Command]
name = "chargedownup_y"
command = ~60$D, U, y
time = 10
[Command]
name = "chargedownup_z"
command = ~60$D, U, z
time = 10
[Command]
name = "FF"
command = F, F
time = 10
[Command]
name = "BB"
command = B, B
time = 10
[Command]
name = "DD"
command = D, D
time = 10
[Command]
name = "DU"
command = D, U
time = 10
[Command]
name = "DUF"
command = D, UF
time = 10
[Command]
name = "DUB"
command = D, UB
time = 10
[Command]
name = "recovery"
command = a+b
time = 1
[Command]
name = "ab"
command = a+b
time = 1
[Command]
name = "ax"
command = a+x
[Command]
name = "by"
command = b+y
[Command]
name = "xy"
command = x+y
time = 1
[Command]
name = "fwd_a"
command = /F,a
time = 1
[Command]
name = "fwd_b"
command = /F,b
time = 1
[Command]
name = "fwd_c"
command = /F,c
time = 1
[Command]
name = "fwd_x"
command = /F,x
time = 1
[Command]
name = "fwd_y"
command = /F,y
time = 1
[Command]
name = "fwd_z"
command = /F,z
time = 1
[Command]
name = "back_a"
command = /B,a
time = 1
[Command]
name = "back_b"
command = /B,b
time = 1
[Command]
name = "back_c"
command = /B,c
time = 1
[Command]
name = "back_x"
command = /B,x
time = 1
[Command]
name = "down_a"
command = /$D,a
time = 1
[Command]
name = "down_b"
command = /$D,b
time = 1
[Command]
name = "down_c"
command = /$D,c
time = 1
[Command]
name = "fwd_ab"
command = /F, a+b
time = 1
[Command]
name = "back_ab"
command = /B, a+b
time = 1
[Command]
name = "a"
command = a
time = 1
[Command]
name = "b"
command = b
time = 1
[Command]
name = "c"
command = c
time = 1
[Command]
name = "x"
command = x
time = 1
[Command]
name = "y"
command = y
time = 1
[Command]
name = "z"
command = z
time = 1
[Command]
name = "charge"
command = /c
time = 1
[Command]
name = "charge1"
command = /D, c
time = 1
[Command]
name = "holdfwd"
command = /$F
time = 1
[Command]
name = "holdback"
command = /$B
time = 1
[Command]
name = "holdup"
command = /$U
time = 1
[Command]
name = "holddown"
command = /$D
time = 1
[Command]
name = "hold_x"
command = /$x
time = 1
[Command]
name = "hold_y"
command = /$y
time = 1
[Command]
name = "hold_z"
command = /$z
time = 1
[Command]
name = "hold_a"
command = /$a
time = 1
[Command]
name = "hold_b"
command = /$b
time = 1
[Command]
name = "hold_c"
command = /$c
time = 1
[Command]
name = "cima"
command = /$U, U
time = 10
[Command]
name = "relfwd"
command = ~F
time = 1
[Command]
name = "relback"
command = ~B
time = 1
[Command]
name = "relup"
command = ~U
time = 1
[Command]
name = "reldown"
command = ~D
time = 1

[Statedef -1]
[State -1]
type = ChangeState
value = 9904
triggerall = Var(7) = 0
triggerall = command = "especial11"
 
triggerall = power >= 3000 
trigger1 = Life  <= 50
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 9000
triggerall = Var(7) = 0
triggerall = command = "especial9"
 
triggerall = power >= 3000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigerall = Var(7) = 0
[State -1]
type = ChangeState
value = 9350
triggerall = Var(7) = 0
triggerall = command = "especial10"
 
triggerall = power >= 2000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 5999
triggerall = Var(7) = 0
triggerall = command = "especial8"
 
triggerall = power >= 2000
trigger1 = stateno = 2000 
 
[State -1]
type = ChangeState
value = 1650
triggerall = Var(7) = 0
triggerall = command = "especial6"
 
triggerall = power >= 1000 
 
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 1550
triggerall = Var(7) = 0
triggerall = command = "especial5"
 
triggerall = power >= 2000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1520
triggerall = Var(7) = 0
triggerall = command = "especial4"
 
triggerall = power >= 3000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1510
triggerall = Var(7) = 0
triggerall = command = "especial3"
 
triggerall = power >= 2000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1500
triggerall = Var(7) = 0
triggerall = command = "especial2"
 
triggerall = power >= 1000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1000
triggerall = Var(7) = 0
triggerall = command = "especial1"
 
triggerall = power >= 1000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 3000
triggerall = Var(7) = 0
triggerall = command = "especial7"
 
triggerall = power >= 2000 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 7115
triggerall = Var(7) = 0
triggerall = command = "ab"
triggerall = pos y < 0
triggerall = P2MoveType = A
triggerall = MoveType = H
triggerall = GetHitVar(hitcount) < 6
triggerall = GetHitVar(hittime) < 40
triggerall = GetHitVar(slidetime) < 40
trigger1 = stateno = 5000
trigger2 = stateno = 5001
trigger3 = stateno = 5002
trigger4 = stateno = 5010
trigger5 = stateno = 5011
trigger6 = stateno = 5012
trigger7 = stateno = 5030
trigger8 = stateno = 5020
[State -1]
type = ChangeState
value = 7120
triggerall = Var(7) = 0
triggerall = command = "xy"
triggerall = command != "holddown"
triggerall = P2StateType != A
triggerall = P2MoveType = A
triggerall = MoveType = H
triggerall = GetHitVar(hitcount) < 6
triggerall = GetHitVar(hittime) < 40
triggerall = GetHitVar(slidetime) < 40
 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 5000
trigger3 = stateno = 5001
trigger4 = stateno = 5002
trigger5 = stateno = 5010
trigger6 = stateno = 5011
trigger7 = stateno = 5012
trigger8 = stateno = 2000
[State -1]
type = ChangeState
value = 7100
triggerall = Var(7) = 0
triggerall = command = "ab"
triggerall = command != "holddown"
triggerall = P2StateType != A
triggerall = P2MoveType = A
triggerall = MoveType = H
triggerall = GetHitVar(hitcount) < 6
triggerall = GetHitVar(hittime) < 40
triggerall = GetHitVar(slidetime) < 40
 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 5000
trigger3 = stateno = 5001
trigger4 = stateno = 5002
trigger5 = stateno = 5010
trigger6 = stateno = 5011
trigger7 = stateno = 5012
[State -1]
type = ChangeState
value = 7110
triggerall = Var(7) = 0
triggerall = command = "xy"
triggerall = command != "holddown"
triggerall = P2StateType != A
triggerall = P2MoveType = A
triggerall = MoveType = H
triggerall = GetHitVar(hitcount) < 6
triggerall = GetHitVar(hittime) < 40
triggerall = GetHitVar(slidetime) < 40
 
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 150
 
[State -1]
type = ChangeState
value = 7060
triggerall = Var(7) = 0
triggerall = command = "super_soco"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 9300
triggerall = Var(7) = 0
triggerall = command = "terremoto"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 7050
triggerall = Var(7) = 0
triggerall = command = "ki_burn"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 7040
triggerall = Var(7) = 0
triggerall = command = "masenko1"
 
trigger1 = statetype = A
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 7035
triggerall = Var(7) = 0
triggerall = command = "masenko"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 7030
triggerall = Var(7) = 0
triggerall = command = "kiai_ho"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 7025
triggerall = Var(7) = 0
triggerall = command = "seeker_fireball"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 7015
triggerall = Var(7) = 0
triggerall = command = "downwards_fireball"
 
 
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 7020
triggerall = Var(7) = 0
triggerall = command = "upwards_fireball"
 
 
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 7010
triggerall = Var(7) = 0
triggerall = command = "stomp_kick"
 
 
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 7000
triggerall = Var(7) = 0
triggerall = command = "rising_punch"
 
 
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 1200
triggerall = Var(7) = 0
triggerall = command = "QCF_b3"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 1100
triggerall = Var(7) = 0
triggerall = command = "QCF_a1"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 1600
triggerall = Var(7) = 0
triggerall = command = "QCF_b2"
 
trigger1 = statetype = A
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 350
triggerall = Var(7) = 0
triggerall = command = "QCF_b"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 325
triggerall = Var(7) = 0
triggerall = command = "xy"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 320
triggerall = Var(7) = 0
triggerall = command = "ab"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 205
triggerall = Var(7) = 0
triggerall = command = "QCF_a"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 1010
triggerall = Var(7) = 0
triggerall = command = "QCF_y"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 1015
triggerall = Var(7) = 0
triggerall = command = "QCF_ya"
 
trigger1 = statetype = A
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1800
triggerall = Var(7) = 0
triggerall = command = "by"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 1700
triggerall = Var(7) = 0
triggerall = command = "ax"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
[State -1]
type = ChangeState
value = 735
triggerall = Var(7) = 0
triggerall = statetype = S
triggerall = Power < 3000
triggerall = ctrl = 1
trigger2 = stateno = 2000
trigger1 = command = "charge"
[State -1]
type = ChangeState
value = 745
triggerall = Var(7) = 0
triggerall = Power < 3000
triggerall = ctrl = 1
trigger1 = command = "hold_c"
trigger1 = stateno = 2000
[State -1]
type = ChangeState
value = 100
triggerall = Var(7) = 0
trigger1 = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 105
triggerall = Var(7) = 0
trigger1 = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 1001
triggerall = Var(7) = 0
trigger1 = command = "FF"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 1051
triggerall = Var(7) = 0
trigger1 = command = "BB"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 106
triggerall = command = "DD"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 1008
triggerall = Var(7) = 0
triggerall = statetype != A
trigger1 = command = "DUB"
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 1007
triggerall = Var(7) = 0
triggerall = statetype != A
trigger1 = command = "DUF"
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 1005
triggerall = Var(7) = 0
trigger1 = command = "DU"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 4000
triggerall = Var(7) = 0
triggerall = statetype = S
triggerall = ctrl = 1
triggerall = p2bodydist X < 5 
trigger1 = command = "fwd_x"
trigger1 = stateno != 100    
trigger1 = p2statetype = S
trigger1 = p2movetype != H
trigger2 = command = "fwd_x"
trigger2 = stateno != 100    
trigger2 = p2statetype = C
trigger2 = p2movetype != H
[State -1]
type = null
value = 950
triggerall = Var(7) = 0
triggerall = statetype = A
triggerall = ctrl = 1
triggerall = p2bodydist X < 9
triggerall = p2bodydist Y > -22
triggerall = p2bodydist Y < 22
triggerall = p2statetype = A
triggerall = p2movetype != H
trigger1 = command = "fwd_b"
trigger2 = command = "back_b"
[State -1]
type = ChangeState
value = 2100
triggerall = Var(7) = 0
trigger1 = statetype != A
trigger1 = ctrl = 1
trigger1 = command = "z"
[State -1]
type = ChangeState
value = 2000
triggerall = Var(7) = 0
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger1 = Pos Y < 0
trigger1 = command = "z"
[State -1]
type = ChangeState
value = 230
triggerall = Var(7) = 0
triggerall = command = "y"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 220
triggerall = Var(7) = 0
triggerall = command = "x"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 225
triggerall = Var(7) = 0
triggerall = command = "b"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
triggerall = p2bodydist X < 5
[State -1]
type = ChangeState
value = 201
triggerall = Var(7) = 0
triggerall = command = "a"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
triggerall = p2bodydist X < 5
[State -1]
type = ChangeState
value = 200
triggerall = Var(7) = 0
triggerall = command = "a"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 210
triggerall = Var(7) = 0
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 430
triggerall = Var(7) = 0
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 420
triggerall = Var(7) = 0
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 400
triggerall = Var(7) = 0
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 410
triggerall = Var(7) = 0
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 640
triggerall = Var(7) = 0
trigger1 = command = "x"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 620
triggerall = Var(7) = 0
trigger1 = command = "y"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 600
triggerall = Var(7) = 0
trigger1 = command = "a"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 610
triggerall = Var(7) = 0
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10200
triggerall = Var(7) = 1
triggerall = command = "a"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 10210
triggerall = Var(7) = 1
triggerall = command = "b"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 10230
triggerall = Var(7) = 1
triggerall = command = "y"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 10220
triggerall = Var(7) = 1
triggerall = command = "x"
triggerall = command != "holddown"
 
trigger1 = statetype = S
trigger1 = ctrl = 1
 
trigger2 = stateno = 2000
[State -1]
type = ChangeState
value = 10400
triggerall = Var(7) = 1
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10420
triggerall = Var(7) = 1
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10430
triggerall = Var(7) = 1
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10410
triggerall = Var(7) = 1
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10600
triggerall = Var(7) = 1
trigger1 = command = "a"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 10610
triggerall = Var(7) = 1
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl = 1

